### ISSUE TITLE
"stop waiting on object lease"

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#428] opened 2015-06-04 10:41 UTC
On running `radicalpilot-stats -m prof -p /Users/mark/Documents/experiments/bluewaters/data/profiling/ -s <sessions>` I got:

```
Session: rp.session.netbook.mark.016590.0014
Number of pilots in session: 1
Processing pilot 'pilot.0014'
Copying 'gsisftp://bw.ncsa.illinois.edu/scratch/sciteam/marksant/radical.pilot.sandbox/rp.session.netbook.mark.016590.0014-pilot.0014/agent.prof' to 'file:///Users/mark/Documents/experiments/bluewaters/data/profiling//rp.session.netbook.mark.016590.0014-pilot.0014.prof'.
Traceback (most recent call last):
  File "/Users/mark/.virtualenv/rp/bin/radicalpilot-stats", line 1083, in <module>
    elif m == 'prof' : prof_session  (db, session, cachedir, profdir)
  File "/Users/mark/.virtualenv/rp/bin/radicalpilot-stats", line 460, in prof_session
    prof_file = saga.filesystem.File(src)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/filesystem/file.py", line 86, in __init__
    _adaptor, _adaptor_state, _ttype=_ttype)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/namespace/entry.py", line 89, in __init__
    url, flags, session, ttype=_ttype)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/saga/adaptors/shell/shell_file.py", line 995, in init_instance
    self.shell = self.lm.lease (lease_tgt, self.shell_creator, self.url) 
  File "/Users/mark/.virtualenv/rp/lib/python2.7/site-packages/radical/utils/lease_manager.py", line 363, in lease
    raise LookupError ("stop waiting on object lease")
LookupError: stop waiting on object lease
```

**Comment by marksantcroos** [comment] 2015-06-04 10:57
Repeatable. The number of sessions = ~20 and the first 10 succeed.

**Comment by andre-merzky** [comment] 2015-06-05 11:11
I added a `file.close()` in the ``prof_session()` method (in `devel-andre`) -- would you mind giving it a try?  I'll try to reproduce it meanwhile...  Thanks!

**Comment by andre-merzky** [comment] 2015-06-05 11:19
Yeah, that seems to solve it all right.  I'll check why the file adaptor is not releasing the shell back to the lease manager after a copy...

**Comment by andre-merzky** [comment] 2015-06-05 11:23
the shell adaptor has that granularity in the moment.  I'll open a SAGA ticket to fix the lease scope, but won't  do it right now if you don't mind.  If the `close()` works for you, please close this ticket in favor of the SAGA one...  Thanks!

**Comment by marksantcroos** [comment] 2015-06-20 14:00
> I added a file.close() in the `prof_session() method (in devel-andre) -- would you mind giving it a try? I'll try to reproduce it meanwhile... Thanks!

Yeah, that works, thanks. Committed that to devel.

**Comment by andre-merzky** [comment] 2016-01-16 00:02
This is probably caused by long leaving leases in the shell_file adaptor, for `self.shell` and `self.local` -- those leases should be made short living...

**Comment by ibethune** [comment] 2017-01-30 15:26
Fixed (at least partly)

**Closed by ibethune** 2017-01-30 15:26 UTC
Labels: bug, shell file adaptor, shell job adaptor
