### ISSUE TITLE
Possible Bug in ShellJob

### ISSUE THREAD

**Issue by rmminusrslash** [radical-cybertools/saga-python#414] opened 2015-02-23 16:34 UTC
Version saga-python-0.25

Possible Bug?

I get an exception from the shell job looking for a script wrapper.sh in  /home/MYUSER/.saga/adaptors/shell_job/wrapper.sh.

Stack trace:

  File "/usr/local/lib/python2.7/dist-packages/saga/job/service.py", line 115, in __init__
    url, session, ttype=_ttype)
  File "/usr/local/lib/python2.7/dist-packages/saga/base.py", line 101, in __init__
    self._init_task = self._adaptor.init_instance (adaptor_state, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/cpi/decorators.py", line 51, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/shell/shell_job.py", line 463, in init_instance
    self.initialize ()
  File "/usr/local/lib/python2.7/dist-packages/saga/adaptors/shell/shell_job.py", line 539, in initialize
    raise saga.NoSuccess ("failed to run bootstrap: (%s)(%s)" % (ret, out))
saga.exceptions.NoSuccess: failed to run bootstrap: (127)(/bin/sh: 0: Can't open /home/lina/.saga/adaptors/shell_job/wrapper.sh

**Comment by andre-merzky** [comment] 2015-02-23 23:37
Hello @rmminusrslash, 

that looks indeed like a problem on the SAGA layer.  I am not sure I understand why that occurs though -- the wrapper script is staged into that directory before it is used.

Would you please run your application again, but before set the following environment variables:

```
export RADICAL_VERBOSE=DEBUG
export RADICAL_UTILS_VERBOSE=DEBUG
export SAGA_VERBOSE=DEBUG
```

and deposit the resulting output log somewhere for review?  Also, what is the `job.Service` url you are using?  Is there anything special about the target system -- like, is $HOME on a shared cluster file system, for example?  Does the directory `/home/lina/.saga/adaptors/shell_job/` exist after the application aborts, and what is in there?

Sorry for the many questions, I'm tapping in the dark here :/

Many thanks, Andre.

**Comment by rmminusrslash** [comment] 2015-02-24 15:46
No problem!

I tried to save you a bit time and debugged the part in question. 

The problem seemed to be in /saga/utils/pty_shell.py. In my case, the temporary file wrapper.sh file is deleted before it is succesfully copied to the .saga folder. If I uncomment the removal of the tmp file in write_to_remote or add a some seconds sleep time in run_copy_to, everything works fine.
So probably one has to make sure the copying is finished before returning from the method.

**Comment by andre-merzky** [comment] 2015-02-24 16:10
Thanks for looking into this!  (although I feel sorry that you had to digg through the pty layer -- its not a nice piece of code... :/ )

On the diagnosis: the staging operation is run synchronously, that it is not finished upon return is unexpected.  But we have seen that on a number of shared file systems lately, specifically on Lustre.  While there is no generic way to handle the problem (its simply not POSIX compliant), its probably sensible to at least put some sanity check in place, to raise an better error (or maybe even to have  some heuristic timeout).

Please use the added sleep for the time being -- I'll keep this ticket open until we manage to get something better in place.

Thanks again! :)

  Andre.

**Comment by rmminusrslash** [comment] 2015-02-25 16:22
Hi Andre,

weirdly enough, I am un a regular Ubuntu 12.04. O.o ...

**Comment by andre-merzky** [comment] 2015-02-26 10:09
Uh, yeah, that should not have any FS level problems (in this context).  I am very sorry, but I am at a loss here.  We definitely have been using that code on a 12.04 box before (although I have non around right now), and either way, I don't think the OS/FS layer is the problem then...

If you have the patience, would you be able to provide us with a debug log?  I am not sure how to triage that further otherwise, unfortunately...

Thanks!

**Comment by rmminusrslash** [comment] 2015-03-06 17:34
Hm. If you already tried 12.04, I will shrug it off to being a special case
on my machine due to god knows what and keep the workaround. As long as
it's not the general case:)

We can close.

Am Donnerstag, 26. Februar 2015 schrieb Andre Merzky :

> Uh, yeah, that should not have any FS level problems (in this context). I
> am very sorry, but I am at a loss here. We definitely have been using that
> code on a 12.04 box before (although I have non around right now), and
> either way, I don't think the OS/FS layer is the problem then...
>
> If you have the patience, would you be able to provide us with a debug
> log? I am not sure how to triage that further otherwise, unfortunately...
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radical-cybertools/saga-python/issues/414#issuecomment-76152507>
> .
>


-- 
Von Gmail Mobile gesendet

**Comment by andre-merzky** [comment] 2015-03-06 18:47
I am relatively sure its not a common case -- as limited as our testing procedure is, this one would have raised a couple of flags...   I tried a couple of things on a ubuntu-12.04 VM, but was not able to reproduce the problem.  So at least its not something which will pop up on every box of this type.  It still concerns me, as Ubuntu 12.04 is not really a strange system, by any means...

Either way, I guess we'll indeed close this ticket, and wait 'til the issue pops up in a more reproducible environment.  Thanks for reporting though, we'll keep our eyes open!

**Closed by andre-merzky** 2015-03-06 18:47 UTC
Labels: Bug, Shell Adaptor
