### ISSUE TITLE
pty shell: should not combine multiple commands on single lines

### ISSUE THREAD

**Issue by marksantcroos** [radical-cybertools/saga-python#444] opened 2015-07-30 13:57 UTC
This seems to be a source of problems as often afterwards we only wait "once" for a prompt, which is only for the first part of the command.

**Comment by andre-merzky** [comment] 2015-07-30 14:27
The shell spawner script has a "BULK" feature which should be used when one wants to run multiple and/or multiline commands.  That will produce return codes (and prompts) for every individual command thus specified.

Where did you stumble over the problem?  Or am I looking at the wrong layer?

**Comment by marksantcroos** [comment] 2015-07-30 14:29
I was talking about things like this: https://github.com/radical-cybertools/saga-python/blob/master/src/saga/utils/pty_shell.py#L999

**Comment by andre-merzky** [comment] 2015-07-30 15:01
Ah, I see -- yes, I agree with that.

**Comment by andre-merzky** [comment] 2015-07-30 15:02
This will fuck with performance though, due to the needed roundtrips.  sftp and scp etc. don't understand bulks, nor the safe concatenation of commands, so we will need one roundtrip per command :/

**Comment by andre-merzky** [comment] 2015-09-15 11:58
One way to clean  this up while preserving performance would be to have `run_sync()` accepting a _list_ of commands, and then either combine them cleanly (`(cmd_1) && (cmd_2)`), or to ensure the right number of prompt detections.  The former one would probably be preferred, as the error mode is better defined (fails on first error).

**Comment by vivek-bala** [comment] 2019-03-27 16:07
Are either of the suggested methods implemented? Couldn't find any related PRs.

**Comment by andre-merzky** [comment] 2019-03-27 22:18
No, and it's unlikely to get implemented soon.  The code has stabilized, it's not much of an issue nowadays.  But this needs to be fixed in v.2 by design.

**Comment by vivek-bala** [comment] 2019-03-28 12:53
Great thanks! I tagged this ticket for v2. Closing for now.

**Closed by vivek-bala** 2019-03-28 12:53 UTC
Labels: topic:communication, type:bug, type:performance, v.2
