### ISSUE TITLE
flushing failed

### ISSUE THREAD

**Issue by dmanubens** [radical-cybertools/saga-python#533] opened 2016-04-14 17:22 UTC
Hello,

I am using this example modified slightly for our HPC resource (http://saga-python.readthedocs.org/en/latest/tutorial/part3.html) and when I launch multiple background scripts I get a flushing failed error.

```
dmanuben@bscearth309:~> module load autosubmit
dmanuben@bscearth309:~> export SAGA_ADAPTOR_PATH=saga.adaptors.shell.shell_job:saga.adaptors.shell.shell_file:autosubmit.platforms.mn_adaptor
dmanuben@bscearth309:~/tmp/testing-saga> SAGA_VERBOSE=DEBUG python saga_example_remote.py & SAGA_VERBOSE=DEBUG python saga_example_remote.py &

2016-04-14 19:05:25,341: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   10] (PROMPT-0->)
2016-04-14 19:05:25,341: radical.saga.cpi    : MainProcess                     : Thread-1       : INFO    : Job monitoring thread updating Job <autosubmit.platforms.mn_adaptor.MNJob object at 0x7fa5ab6e62d0> (state: Running)
2016-04-14 19:05:28,344: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : flush: [    4] [     ] (flush pty read cache)
2016-04-14 19:05:28,344: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : flush: [    4] [     ] (flush pty read cache)
2016-04-14 19:05:28,446: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : run_sync: bjobs -noheader 1741003
2016-04-14 19:05:28,446: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : run_sync: bjobs -noheader 1741004
2016-04-14 19:05:28,447: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : write: [    4] [   24] (bjobs -noheader 1741003\n)
2016-04-14 19:05:28,447: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : write: [    4] [   24] (bjobs -noheader 1741004\n)
2016-04-14 19:05:28,566: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   82] (1741003 bsc3270 DONE  sequential login2      s01         *MYOUTPUT  Apr 14 19:04\n)
2016-04-14 19:05:28,568: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   82] (1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04\n)
2016-04-14 19:05:28,570: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   10] (PROMPT-0->)
2016-04-14 19:05:28,570: radical.saga.cpi    : MainProcess                     : Thread-1       : INFO    : Job monitoring thread updating Job <autosubmit.platforms.mn_adaptor.MNJob object at 0x7f51412692d0> (state: Done)
2016-04-14 19:05:28,571: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   10] (PROMPT-0->)
2016-04-14 19:05:28,571: radical.saga.cpi    : MainProcess                     : Thread-1       : INFO    : Job monitoring thread updating Job <autosubmit.platforms.mn_adaptor.MNJob object at 0x7fa5ab6e62d0> (state: Running)
Job State : Done
Exitcode  : None
2016-04-14 19:05:31,574: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : flush: [    4] [     ] (flush pty read cache)
2016-04-14 19:05:31,575: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : read : [    4] [   41] (Shared connection to mn2.bsc.es closed.\n)
2016-04-14 19:05:31,575: radical.saga.pty    : MainProcess                     : Thread-1       : WARNING : flush: [    4] [   40] (discard data: 'Shared connection to mn2.bsc.es closed.
')
2016-04-14 19:05:31,615: radical.saga.pty    : MainProcess                     : Thread-1       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (*MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2016-04-14 19:05:31,615: radical.saga.cpi    : MainProcess                     : Thread-1       : WARNING : Exception caught in job monitoring thread: read from process failed '[Errno 5] Input/output error' : (*MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2016-04-14 19:05:31,615: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : flush: [    4] [     ] (flush pty read cache)
2016-04-14 19:05:31,616: radical.saga.pty    : MainProcess                     : Thread-1       : ERROR   : flushing failed
Traceback (most recent call last):
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (*MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2016-04-14 19:05:31,616: radical.saga.cpi    : MainProcess                     : Thread-1       : WARNING : Exception caught in job monitoring thread: read from process failed '[Errno 5] Input/output error' : (*MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->1741004 bsc3270 RUN   sequential login2      s01         *MYOUTPUT  Apr 14 19:04
PROMPT-0->Shared connection to mn2.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
2016-04-14 19:05:31,616: radical.saga.pty    : MainProcess                     : Thread-1       : DEBUG   : flush: [    4] [     ] (flush pty read cache)
```

**Comment by dmanubens** [comment] 2016-04-18 17:28
I attach both debug logs for better understanding...

[1.err.fail.txt](https://github.com/radical-cybertools/saga-python/files/224322/1.err.fail.txt)
[2.err.fail.txt](https://github.com/radical-cybertools/saga-python/files/224323/2.err.fail.txt)

Any help would be welcome...

**Comment by andre-merzky** [comment] 2016-04-19 01:50
Hi @dmanubens, 

It seems that in one of your scripts and ssh channel is disappearing, and thus things fall apart.  The reason as to *why* the channel disappears are not obvious, unfortunately.

In general, SAGA tries to be conservative in the number of ssh channels used to any target host -- but ssh client and server configurations are very unpredictable, so SAGA never knows about the actual available number of connections.  When you run multiple SAGA codes concurrently, each will compete with the other for the ssh channels available.

From your description I would assume that the problem only occurs on multiple, concurrent scripts?  If that is so, I actually don't have a better proposal than to avoid that.  But, to be somewhat more productive, you should be able to run multiple jobs from within the *same* script.  May I ask why you opted for running multiple scripts individual instead?

It would be great if you could share your script, I'd love to try to reproduce the problem.

Best, Andre.

**Comment by dmanubens** [comment] 2016-04-19 09:36
Hi @andre-merzky ,

Thanks for your explanations. Yes indeed only occurs on multiple concurrent scripts and unfortunately not always. However this is the way we work with our 'meta-scheduler' Autosubmit (https://pypi.python.org/pypi/autosubmit) since every user launches several concurrent experiments from the same host, and each experiment creates a SAGA service to submits many jobs through. I have decided to download the example script and try concurrent runs. I have been able to reproduce it several times: `SAGA_VERBOSE=DEBUG python saga_example_remote.py & SAGA_VERBOSE=DEBUG python saga_example_remote.py &`. In this example I am using an adaptor created by @jvegasbsc for MareNostrum 3 since I don't have access to any other HPC right now. I attach both the script and the adaptor (although I don't think it is a problem on the adaptor). Could you try to reproduce the problem using any other adaptor?

Best regards
[mn_adaptor.py.txt](https://github.com/radical-cybertools/saga-python/files/225611/mn_adaptor.py.txt)
[saga_example_remote.py.txt](https://github.com/radical-cybertools/saga-python/files/225612/saga_example_remote.py.txt)

**Comment by dmanubens** [comment] 2016-04-19 14:14
Hi @andre-merzky ,
I have also tried same concurrent scripts above but just via SSH (removing the mn adaptor) and I have similar error in one of the scripts:
```
2016-04-19 16:03:26,185: radical.saga.cpi    : MainProcess                     : Thread-1       : DEBUG   : read : [    5] [   41] (Shared connection to mn2.bsc.es closed.\n)
2016-04-19 16:03:26,185: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [   41] (Shared connection to mn2.bsc.es closed.\n)
2016-04-19 16:03:26,185: radical.saga.cpi    : MainProcess                     : Thread-1       : WARNING : monitoring channel noise: Shared connection to mn2.bsc.es closed.
2016-04-19 16:03:26,185: radical.saga.cpi    : MainProcess                     : MainThread     : WARNING : flush: [    4] [   40] (discard data: 'Shared connection to mn2.bsc.es closed.
')
2016-04-19 16:03:26,187: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : flushing failed
Traceback (most recent call last):
  File "/home/Earth/dmanuben/venvs/as_320/lib/python2.7/site-packages/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/home/Earth/dmanuben/venvs/as_320/lib/python2.7/site-packages/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
```
while sometimes a also different error appears:
```
2016-04-19 16:03:25,461: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [   46] (/bin/sh ~/.saga/adaptors/shell_job/wrapper.sh\n)
2016-04-19 16:03:25,484: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [   12] (PID: 27223\n)
2016-04-19 16:03:25,765: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [   95] (mkfifo: cannot create fifo `/home/bsc32/bsc32704/.saga/adaptors/shell_job//fifo': File exists\n)
2016-04-19 16:03:25,765: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : read : [    4] [   12] (PROMPT-0->\n)
2016-04-19 16:03:25,766: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : flush: [    4] [     ] (flush pty read cache)
2016-04-19 16:03:25,766: radical.saga.cpi    : MainProcess                     : MainThread     : WARNING : flush: [    4] [    1] (discard data: '
')
2016-04-19 16:03:25,867: radical.saga.cpi    : MainProcess                     : MainThread     : DEBUG   : write: [    4] [    5] (exit\n)
2016-04-19 16:03:25,867: radical.saga.cpi    : MainProcess                     : MainThread     : ERROR   : host bootstrap failed - no pid (PID: 27223
mkfifo: cannot create fifo `/home/bsc32/bsc32704/.saga/adaptors/shell_job//fifo': File exists
)
An exception occured: (NoSuccess) host bootstrap failed - no pid (PID: 27223
mkfifo: cannot create fifo `/home/bsc32/bsc32704/.saga/adaptors/shell_job//fifo': File exists
) (/home/Earth/dmanuben/venvs/as_320/lib/python2.7/site-packages/saga/adaptors/shell/shell_job.py +557 (initialize)  :  raise saga.NoSuccess ("host bootstrap failed - no pid (%s)" % out))
```

Thanks a lot for your help.

[saga_example_ssh.py.txt](https://github.com/radical-cybertools/saga-python/files/226052/saga_example_ssh.py.txt)

[s2.err.fail.txt](https://github.com/radical-cybertools/saga-python/files/226054/s2.err.fail.txt)
[s1.err.fail.txt](https://github.com/radical-cybertools/saga-python/files/226055/s1.err.fail.txt)

**Comment by andre-merzky** [comment] 2016-04-27 17:32
Hmm, the fifo creation seems also to be a race condition.  I'll open another ticket for this one, that likely needs a creation lock.  Thanks!

About the original problem: yes, let me try to reproduce this.  Either way though, that will be difficult to fix.  The pty layer, and connection management, has been tripping us very frequently, and more so in concurrent setups.  We do have some ideas on how to refactor that (rather central) piece of code, but alas, could not yet allocate the manpower to approach this thoroughly.  So, lets see if we can find yet another partial fix :P 

Are all ssh connections running under the same user ID, and toward the same ID on the target machines?

**Comment by dmanubens** [comment] 2016-05-02 13:16
Hello,

Yes all ssh connections are running under the same user ID and towards the same ID on the target.
I haven't been able to reproduce it using 2 user ID towards the same ID on the target, neither using 1 user ID towards 2 different ID on the target.

Best regards

**Comment by dmanubens** [comment] 2016-05-06 10:28
Hi again,

We have detected that two concurrent services running for long time can live together until one of them finishes. The first one finishes and closes the service, just then, the other that was expected to run longer crashes. Any ideas for partially fixing this ?

4 of 7 jobs remaining (22:45)
2016-05-05 22:45:21,038 Sleep: 10
2016-05-05 22:45:21,038 Number of retrials: 0
[CRITICAL] 2016-05-05 22:45:21,041 Unhandled exception on Autosubmit: read from process failed '[Errno 5] Input/output error' : (798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))
Traceback (most recent call last):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 283, in parse_args
    return Autosubmit.run_experiment(args.expid)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/autosubmit.py", line 598, in run_experiment
    if job.status != job.update_status(platform.check_job(job.id)):
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/platforms/platform.py", line 440, in check_job
    if jobid not in self.service.jobs:
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/job/service.py", line 378, in list
    return self._adaptor.list (ttype=ttype)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/adaptors/cpi/decorators.py", line 57, in wrap_function
    return sync_function (self, *args, **kwargs)
  File "/shared/earth/software/autosubmit/3.3.1-foss-2015a-Python-2.7.9/lib/python2.7/site-packages/autosubmit-3.3.1-py2.7.egg/autosubmit/platforms/mn_adaptor.py", line 865, in list
    ret, out, _ = self.shell.run_sync("%s -a -noheader" % 'bjobs')
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_shell.py", line 648, in run_sync
    self.pty_shell.flush ()
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 174, in flush
    tmp = self.read (timeout=0.1)
  File "/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py", line 679, in read
    % (e, self.tail))
NoSuccess: read from process failed '[Errno 5] Input/output error' : (798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Job <1798272> is not found
PROMPT-0->Shared connection to mn1.bsc.es closed.
) (/shared/earth/software/Python/2.7.9-foss-2015a/lib/python2.7/site-packages/saga_python-0.40-py2.7.egg/saga/utils/pty_process.py +679 (read)  :  % (e, self.tail)))

**Comment by dmanubens** [comment] 2016-05-12 13:32
Hi @andre-merzky , 
We decided to implement a retrial mechanism in our code that captures the exception and waits a few seconds. After this wait it seems in most cases that the channel gets alive again and we can continue the instance that was failing. e.g.:

```
        retries = 30
        while True:
            if retries > 0:
                try:
                    myjob.wait()
                    break
                except saga.SagaException:
                    retries -= 1
                    time.sleep(5)
            else:
                break

```

**Comment by andre-merzky** [comment] 2016-05-23 11:42
Hi @dmanubens, 

sorry that it took so long to get back to this ticket :/ 

I am glad that you found a workaround!  That one makes sense: the lease manager will interpret the delayed retry as a new connection request, and will start from scratch...

**Comment by dmanubens** [comment] 2016-06-07 14:54
Unfortunately the workaround does not always work.
We can not use anymore saga from Autosubmit before having a fix for the pty layer and connection management.

**Comment by andre-merzky** [comment] 2016-06-07 19:11
That is unfortunate indeed :/  

I tried to reproduce the problem, but was not able to: freeing connections in one thread seemed not to disturb connections in another thread.  Do you happen to have a standalone code snippet which reproduces this?

If not, I would like to ask you to run an instance with `RADICAL_SAGA_PTY_VERBOSE=DEBUG`.  Please send me the resulting log files (you can direct all logging to a file with `RADICAL_LOG_TGT=/tmp/radical.log`).

Thanks, Andre.

**Comment by andre-merzky** [comment] 2016-06-07 19:13
PS.: you may want to make sure that no passwords etc. end up in the log files -- the PTY logging stores most of the strings which go over the wire, too!

**Comment by dmanubens** [comment] 2016-06-08 09:30
Hi @andre-merzky , did you tried with the code snipped I posted here?: https://github.com/radical-cybertools/saga-python/issues/533#issuecomment-211939663 
You also can find there two log files using `RADICAL_SAGA_PTY_VERBOSE=DEBUG`. 
However I didn't try with newer version of saga 0.41... I will try to reproduce it again.
We have also prepared a shell script to launch several threads... It is useful also to reproduce https://github.com/radical-cybertools/saga-python/issues/527 that is also blocking us....
I attach here this  script and the code snippet with the attempted workaround with delayed retries.

[saga_example_turing.py.txt](https://github.com/radical-cybertools/saga-python/files/304427/saga_example_turing.py.txt)
[stress_test.sh.txt](https://github.com/radical-cybertools/saga-python/files/304426/stress_test.sh.txt)

**Comment by larissaleite** [comment] 2017-10-18 12:37
@itomaldonado @andre-merzky quick update on this issue: I have run several tests with the scripts posted by @dmanubens with version 0.46.1 and the `flushing failed` error still remains. Also, a few times I got I/O error stating insufficient system resources: 

```
2017-10-18 14:33:57,696: radical.saga.pty    : MainProcess                     : MainThread     : DEBUG   : Traceback (most recent call last):
  File "/home/lbatista/saga-env/local/lib/python2.7/site-packages/saga/utils/pty_shell.py", line 688, in run_sync
    fret, match = self.pty_shell.find ([prompt], timeout=-1.0)  # blocks
  File "/home/lbatista/saga-env/local/lib/python2.7/site-packages/saga/utils/pty_process.py", line 790, in find
    raise ptye.translate_exception (e, "(%s)" % data)

NoSuccess: Insufficient system resources: read from process failed '[Errno 5] Input/output error'
```

**Comment by vivek-bala** [comment] 2019-03-27 13:39
Hey @andre-merzky , based on the descriptions here, the fix needs to be in the pty layer. Would you agree? What is the status of the pty layer in the context of version 2?

**Comment by andre-merzky** [comment] 2019-03-27 22:55
This will likely be fixed in v.2 as the connection handling is fundamentally different and does not rely on multiplexing anymore.

**Comment by vivek-bala** [comment] 2019-03-28 12:43
Great, thanks for the info. Closing the issue for the time being. Please reopen if this reoccurs.

**Closed by vivek-bala** 2019-03-28 12:43 UTC
Labels: comp:shell_job, topic:communication

**Comment by vivek-bala** [comment] 2019-03-28 12:55
Added v2 tag.
