### ISSUE TITLE
Launched jobs from previous sessions are detected but their status is not updated

### ISSUE THREAD

**Issue by luis-rr** [radical-cybertools/saga-python#415] opened 2015-03-03 12:52 UTC
This is with the shell adaptor.
Repro steps:
1 Open a session
2 Launch a job that requires some time
3 Close the session
4 Open a new one
5 Query the state of that job

Result: The jobid is accepted but the state of the job is never updated: it is stuck in the 'running' state.

This is a regression. It used to work differently in previous saga versions: the jobid was accepted and the state would continue to be updated.

Using git bisect, it seems that this bug was introduced into master around August. One of:
d7f785d324f2c36f90f34df244fb5eb09d598000
5f46143c20fa0c8a576ddec3bd28d993a162908b *
f142c609054b667a88a4eeacd4afafc7c9dd9717
30698adc8be0bd3a907f2b70c88719274c8568ba *
a2b21619a0675ad5aaa3cb64310328e19e45c58d
8021e305afeaf4421e17e376fde7a48ef9e145cd

Very likely, with one of the two merges from devel *

This is a script that lets you reproduce the problem.
```python
import sys
import time
import saga

def fire_and_forget(wait):
    session = saga.Session()
    service = saga.job.Service(rm='local://localhost', session=session)
    description = saga.job.Description()
    description.executable = 'sleep'
    description.arguments = [wait]
    job = service.create_job(description)
    job.run()
    service.close()
    return job.id


def pickup(jobid, wait):
    session = saga.Session()
    service = saga.job.Service(rm='local://localhost', session=session)
    job = service.get_job(jobid)
   
    i = 0
    while job.state == 'Running' and i < wait:
        i += 1
        print i, 'job state:', job.state
        time.sleep(1)
    
    if job.state == 'Running':
        print 'Job should have finished :('
        return 1
    else:
        print 'success!'
        return 0



if __name__ == "__main__":
    waittime = 5
    jobid = fire_and_forget(waittime)
    sys.exit(pickup(jobid, waittime + 5))

```

**Comment by andre-merzky** [comment] 2015-03-03 16:04
Hi Luis, 

thanks for the ticket.  I can confirm the issue.  The cause seems to be that the monitoring process dies with the end of the session, and thus fails to update job state later on.  That should not happen (the monitor script is supposed to run in a different process group, and should be uneffected by the session and submission script closing).

**Comment by andre-merzky** [comment] 2015-03-04 02:21
Hi again, 

this is fixed now -- the process monitor  now explicitly ignores SIGHUP, and thus survives the session shutdown (which closes the grand-grand-grand-parent shell).  I am not exactly sure why SIGHUP is not ignored in the first place, as the monitor runs in its own process groups -- but either way, it makes sense to set this explicitly.

Thanks for the example code, that helped a lot.  It should not succeed with the current devel branch, and the fix will make it into the next release (which is upcoming shortly).

**Closed by andre-merzky** 2015-03-04 02:21 UTC
Labels: Bug, Shell Adaptor

**Comment by luis-rr** [comment] 2015-03-04 08:24
Wow, that was fast. Thanks for the quick response Andre.
